### ISSUE TITLE
Teste `Example` às vezes falha

### ISSUE THREAD

**Issue by ramalho** [ThoughtWorksInc/runas#1]
Teste `Example` falha, possivelmente por interferência da saída da função `progresso` na saída padrão. Mas o problema se manifesta somente às vezes, veja dois acionamentos dos testes, um logo após o outro: o segundo passa OK. Como resolver isso?

```
$ go test
./TEST1483367418448201946-UnicodeData.txt não encontrado
baixando http://www.unicode.org/Public/UNIDATA/UnicodeData.txt
.........................
--- FAIL: Example (1.30s)
got:
/Users/lramalho/UnicodeData.txt não encontrado
baixando http://www.unicode.org/Public/UNIDATA/UnicodeData.txt
........
U+20A2	₢	CRUZEIRO SIGN
want:
U+20A2	₢	CRUZEIRO SIGN
FAIL
exit status 1
FAIL	github.com/labgo/runas	5.256s
$ go test
./TEST1483367451502712367-UnicodeData.txt não encontrado
baixando http://www.unicode.org/Public/UNIDATA/UnicodeData.txt
................
PASS
ok  	github.com/labgo/runas	2.626s
```

**Comment by andrewsmedina** [comment]
O teste falha sempre na primeira vez. 

Em alguns testes a origem do arquivo `UnicodeData.txt` não é definido. Com isso, na primeira vez que os testes são rodados é feito o download o `UnicodeData.txt` no $HOME.

Nas outras vezes não da erro porque o arquivo já existe e o download não é mais necessário. Se você sempre apagar o $HOME/UnicodeData.txt antes de rodar os testes, eles sempre falharão.

**Comment by ramalho** [comment]
Oi, Andrews, muito grato pelo seu interesse em ajudar! Muito bem observado, é isso mesmo o que acontece. Como você sugere refatorar os testes para resolver este problema? Talvez sejam duas refatorações: uma na sequência do tutorial, onde queremos começar simples e não se preocupar com o download, e outra no passo final (passo 7). Vou pensar nisso, mas aceito sugestões! Valeu!

**Comment by ramalho** [comment]
Resolvido! Havia um teste (TestAbrirUCD_local) que usava o caminho do diretório corrente em vez do caminho gerado por obterCaminhoUCD. Com esse ajuste, não ocorre mais a falha pois quando o teste Example roda pela primeira vez, o TestAbrirUCD_local já baixou o arquivo.

**Comment by ramalho** [comment]
Resolvido! Havia um teste (TestAbrirUCD_local) que usava o caminho do diretório corrente em vez do caminho gerado por obterCaminhoUCD. Com esse ajuste, não ocorre mais a falha pois quando o teste Example roda pela primeira vez, o TestAbrirUCD_local já baixou o arquivo.
